site_name: Bode integral
nav:
  - Home: index.md
  - Projects: 
    - projects/Project1_msim.md
    - projects/Project2_propeller.md
    - projects/Project3_p51.md
  - Blog:
    - blog/index.md
  - About: about.md
theme:
    name: material
    language: en
    icon:
        logo: material/waveform
    favicon: img/waveform.svg
    features:
        - navigation.tabs
        - navigation.sections
        - navigation.top
        - content.code.copy
    palette:
        # Palette toggle for light mode
        - scheme: default
          primary: blue
          accent: indigo
          toggle:
            icon: material/toggle-switch 
            name: Switch to dark mode
            

        # Palette toggle for dark mode
        - scheme: slate
          primary: grey
          accent: indigo
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to light mode
plugins:
  - search
  - blog
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.highlight:
      linenums: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css  